config = {
    'execution': None,
    'timeout': None,
    'debug_stop': None,
    'server_connection': None,
    'server_address': None,
    'release': None,
    'log_level': 'INFO',
    'broker_id': '',
    'broker_pw': '',
    'browser': None,
    'device': None,
    'username': None,
    'access_key': None,
    'tunnel_id': None,
    'selenium_port': None,
    'build_tag': None,
    'mail': None,
    'm_version': None,
    'email_add': None,
    'SCOPES': None,
    'storage_file': None,
    'client_secret': None,
    'q_from': None,
    'q_sub_ssq': None,
    'q_sub_cq': None,
    'q_sub_scq': None,
    'q_sub_baa': None,
    'q_ghi_hcc_sub': None,
    'q_ghi_from': None,
    'reportfolder': None,
    'logfolder': None,
    'screenshotfolder': None,
    'screenshot': False,
    'environment': None,
    'xsl': None,
    'reportname': None,
    'convert': None,
    'sso': False
}

dirs = {
    'wkd': None,
    'cwd': None
}

report = {}

ts_data = {
    'uri': None,
    'data': None,
    'tsname': None,
    'tcname': None,
    'desc': None,
    'type': None,
    'zipcode': None,
    'county': None,
    'state': None,
    'applicants': None,
    'applicantsnum': None,
    'applicantsdob': None,
    'applicantsage': None,
    'applicantstobacco': None,
    'plans': None,
    'plandict': None,
    'applicantheightft': None,
    'applicantheightin': None,
    'applicantweightlbs': None,
    'primaryfname': None,
    'primarylname': None,
    'brokerid': None,
    'brokerpwd': None
}

states = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'DC': 'District of Columbia',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming'
}

counties = {
    '71601': 'JEFFERSON',
    '83702': 'ADA',
    '46278': 'MARION',
    '59001': 'STILLWATER',
    '97086': 'CLACKAMAS'
}

pa_data = {
    'state': None,
    'zipcode': None,
    'tsname': None,
    'tcname': None,
    'desc': None,
    'type': None,
    'uri': None,
    'planlist': None
}

ws = {
    'server': None,
    'client': None
}
