repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
    - id: check-json
    - id: check-yaml
    - id: trailing-whitespace
    - id: end-of-file-fixer
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.6
  hooks:
    - id: forbid-tabs
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
    - id: black
      args: ['--config=pyproject.toml', '-v']
- repo: local
  hooks:
    - id: flake8
      name: flake8
      language: system
      entry: poetry run flake8
      types: [python]
    - id: isort
      args: ["--profile", "black"]
      name: isort
      language: system
      entry: poetry run isort
      types: [ python ]
