
browser:
  name: chrome
  headless: false
  size: 1920,1080

device: ~
environment: model
execution_mode: local
log_level: INFO

directory:
  logs: logs
  screenshots: screenshots
  reports: reports
