name: build
on: [pull_request]

jobs:
  create-virtualenv:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'

    - run: |
        pip install 'poetry==1.1.12'
        poetry install


  linter:
    needs: create-virtualenv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - uses: syphar/restore-virtualenv@v1
      id: cache-virtualenv

    - name: pre-commit
      run: |
        pre-commit run check-json
        pre-commit run check-yaml
        pre-commit run trailing-whitespace
        pre-commit run end-of-file-fixer
        pre-commit run forbid-tabs
        flake8
        isort . --diff --check-only
        black -v --check --diff .
