name: deploy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: pull-request
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9.2"
    - name: Install dependencies
      run: |
        pip install 'poetry==1.1.12'
        poetry install
    - run: make
    - name: self test newly built action
      uses: ./
    - run: make push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
